[package]
name = "modem-connector"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.28"
serde = "1.0.228"
simple_logger = "5.1.0"
tokio = {version = "1.48.0", features=["macros", "rt-multi-thread"]}
zbus = "5.12.0"
